package com.stuff;

/**
 * Created by adam on 6/9/2017.
 */
public enum StateAction {
    REPORT_ADDED,
    ANALYST_REVIEWED_REPORT,
    COUNTERMEASURE_RECOMMENDED,
    COUNTERMASURER_EXPEDITED,
    YES_COUNTERMEASURE_RECOMMENDED,
    NO_COUNTERMASURE_NOT_RECOMMENDED,
    WCF_TOOL_SELECTED,
    IP_TOOL_SELECTED
}
